services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: studhub
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/studhub
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
  cpp:
    build: ./database
    depends_on:
      - db
    environment: 
      DATABASE_URL: "host=db port=5432 dbname=studhub user=user password=pass"

volumes:
  db_data: